In [1]:
import pandas as pd
import glob

In [ ]:
files = glob.glob("data*.csv")
df_list = []

for file in files:
    df = pd.read_csv(file, encoding="utf-8-sig")
    df_list.append(df)

# Fusionner tous les dataframes
df_total = pd.concat(df_list, ignore_index=True)

# Sauvegarder le dataset final
df_total.to_csv("dataset_total.csv", index=False)

print("Fusion terminée !")
print("Nombre total de lignes :", df_total.shape[0])
print("Nombre total de colonnes :", df_total.shape[1])

Fusion terminée !
Nombre total de lignes : 10368
Nombre total de colonnes : 30

In [3]:
df.head(5)

,position,channelId,channelTitle,videoId,publishedAt,publishedAtSQL,videoTitle,videoDescription,tags,videoCategoryId,...,licensedContent,hasPaidProductPlacement,locationDescription,latitude,longitude,viewCount,likeCount,dislikeCount,favoriteCount,commentCount
0,1,UCqUO3O-XAiM6vpC5qScVjww,Taha Essou,vYYRiq8e0uA,2026-04-17T18:25:50Z,2026-04-17 18:25:50,Inside the Secret World of Football Agents - أ...,NaN,NaN,22,...,1.0,NaN,NaN,NaN,NaN,146858,3429,NaN,0,148
1,2,UCqUO3O-XAiM6vpC5qScVjww,Taha Essou,KQchSfDra1s,2026-04-11T13:57:37Z,2026-04-11 13:57:37,ICONS OF PORSCHE FESTIVAL - جنة سيارة الپورشا 🚘,NaN,NaN,22,...,1.0,NaN,NaN,NaN,NaN,156821,3756,NaN,0,126
2,3,UCqUO3O-XAiM6vpC5qScVjww,Taha Essou,Y8t83gDXY9w,2026-04-05T13:57:07Z,2026-04-05 13:57:07,FORUM NATIONAL DE L'ENSEIGNANT- أكثر من 3000 أ...,NaN,NaN,22,...,1.0,NaN,NaN,NaN,NaN,98937,2608,NaN,0,172
3,4,UCqUO3O-XAiM6vpC5qScVjww,Taha Essou,QVnfvXVgHcE,2026-04-01T17:04:13Z,2026-04-01 17:04:13,FIRST SHOW ON TV - 2M وراء ستار برنامج في #Ntl...,NaN,NaN,22,...,1.0,NaN,NaN,NaN,NaN,41276,1052,NaN,0,57
4,5,UCqUO3O-XAiM6vpC5qScVjww,Taha Essou,UAAfs7ErSZg,2026-03-18T16:36:53Z,2026-03-18 16:36:53,HISTORICAL DAY - ربحنا كأس إفريقيا من بعد شهري...,Follow me on instagram : tahaessou,NaN,22,...,1.0,NaN,NaN,NaN,NaN,138564,3591,NaN,0,198

In [4]:
df_total.head()
df_total.info()
df_total[['channelTitle']].describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10368 entries, 0 to 10367
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   position                 10368 non-null  int64
 1   channelId                10368 non-null  object
 2   channelTitle             10368 non-null  object
 3   videoId                  10368 non-null  object
 4   publishedAt              10368 non-null  object
 5   publishedAtSQL           10368 non-null  object
 6   videoTitle               10368 non-null  object
 7   videoDescription         9158 non-null   object
 8   tags                     7375 non-null   object
 9   videoCategoryId          10368 non-null  int64
 10  videoCategoryLabel       10368 non-null  object
 11  topicCategories          7176 non-null   object
 12  duration                 10368 non-null  object
 13  durationSec              10368 non-null  int64
 14  dimension                10368 non-null  object
 15  definition               10368 non-null  object
 16  caption                  10368 non-null  bool
 17  defaultLanguage          10368 non-null  object
 18  defaultLAudioLanguage    10368 non-null  object
 19  thumbnail_maxres         9730 non-null   object
 20  licensedContent          9791 non-null   float64
 21  hasPaidProductPlacement  19 non-null     float64
 22  locationDescription      164 non-null    object
 23  latitude                 164 non-null    float64
 24  longitude                164 non-null    float64
 25  viewCount                10368 non-null  int64
 26  likeCount                10362 non-null  float64
 27  dislikeCount             0 non-null      float64
 28  favoriteCount            10368 non-null  int64
 29  commentCount             10356 non-null  float64
dtypes: bool(1), float64(7), int64(5), object(17)
memory usage: 2.3+ MB

       channelTitle
count         10368
unique           12
top     Farouk Life
freq           1998